# Generated by Django 5.1.6 on 2025-03-10 10:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=255, verbose_name='Name'), max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Too short, 5 symbols is minimum'), django.core.validators.MaxLengthValidator(100, message='Too long, 100 symbols is maximum')], verbose_name='Slug'),
        ),
    ]
